name: dabl_query
version: 0.1.2
author: Nathan Kerr <nathankerr@gmail.com>
description: The DABL Query generator. Object-oriented query creator.
homepage: https://github.com/TheBosZ/dabl-query
dependencies:
  ddo:
    path: ../pdodart
dev_dependencies:
  unittest: any
